//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/13/2023 12:27:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace AccountsModel
{
    public partial class AccountLogin {

        public AccountLogin()
        {
            OnCreated();
        }

        public int LoginId { get; set; }

        public string Account { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public string Website { get; set; }

        public int FkMasterId { get; set; }

        public virtual MasterAccount MasterAccount { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
