//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/14/2023 2:12:47 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace AccountsModel
{
    public partial class MasterAccount {

        public MasterAccount()
        {
            this.AccountLogins = new List<AccountLogin>();
            OnCreated();
        }

        public int MasterId { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public string Email { get; set; }

        public string AspUserID { get; set; }

        public virtual IList<AccountLogin> AccountLogins { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
